apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pvc
spec:
  storageClassName: ""
  volumeName: home-assistant-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/home-assistant
